using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AppUI.Models;

namespace AppUI.Services
{
    public static class IniConfigService
    {
        private static readonly object _syncLock = new();
        private static CancellationTokenSource? _debounceCts;

        public static string GenerateCompleteIni(GameProfile profile)
        {
            var sb = new StringBuilder();
            sb.AppendLine("; AetherPulse Runtime Configuration File");
            sb.AppendLine("; Generated by AetherPulse Engine Configuration Manager");
            sb.AppendLine();

            sb.AppendLine("[Pacing]");
            sb.AppendLine($"enablePacing={(profile.PacingEnabled ? "1" : "0")}");
            sb.AppendLine($"targetFps={profile.TargetFpsCap}");
            sb.AppendLine($"halfInterval={(profile.HalfIntervalCadenceEnabled ? "1" : "0")}");
            sb.AppendLine($"antiLag2={(profile.AntiLag2Enabled ? "1" : "0")}");
            sb.AppendLine($"hudPreservationMask={(profile.HudProtection ? "1" : "0")}");
            sb.AppendLine($"emaAlpha={profile.EmaAlpha:F3}");
            sb.AppendLine($"enforceFlipDiscard={(profile.ForceFlipDiscard ? "1" : "0")}");
            sb.AppendLine($"maxFrameLatency={profile.MaxFrameLatency}");
            sb.AppendLine($"spinYieldPrecisionUs={profile.SpinYieldMicroseconds}");
            sb.AppendLine();

            sb.AppendLine("[Upscaling]");
            sb.AppendLine($"nativeAA={(profile.NativeAA ? "1" : "0")}");
            sb.AppendLine($"reactiveMaskOptimization={(profile.ReactiveMask ? "1" : "0")}");
            sb.AppendLine($"overrideRCAS={(profile.EnableRCASOverride ? "1" : "0")}");
            sb.AppendLine($"rcasSharpness={profile.Sharpness:F2}");
            sb.AppendLine($"autoCalculateMipLod={(profile.AutoLODBias ? "1" : "0")}");
            sb.AppendLine($"manualMipLodBias={profile.TextureLODBias:F2}");
            sb.AppendLine($"reactiveMaskSensitivity={profile.ReactiveMaskSensitivity:F2}");
            sb.AppendLine($"drsFloorScale={profile.ClampMinRenderScale}");
            sb.AppendLine();

            sb.AppendLine("[RayRegeneration]");
            sb.AppendLine($"enableRayRegen={(profile.RayRegenEnabled ? "1" : "0")}");
            sb.AppendLine($"fp16RadianceClamp=1");
            sb.AppendLine($"enableNRC={(profile.NeuralRadianceCache ? "1" : "0")}");
            sb.AppendLine($"denoiseReflection={(profile.DenoiseReflections ? "1" : "0")}");
            sb.AppendLine($"denoiseShadowAO={(profile.DenoiseShadows ? "1" : "0")}");
            sb.AppendLine($"glossyRadianceFilter={(profile.GlossyRadianceFilter ? "1" : "0")}");
            sb.AppendLine($"hdrExposureClamping=1");
            sb.AppendLine($"perceptualColorCorrection=1");
            sb.AppendLine($"disocclusionGhostingFilter=1");
            sb.AppendLine($"roughnessThreshold={profile.RoughnessThreshold:F2}");
            sb.AppendLine($"spatialWaveletIterations={profile.SpatialFilterPasses}");
            sb.AppendLine($"temporalHistoryWeight={profile.TemporalWeight:F2}");
            sb.AppendLine($"depthSigma={profile.DepthSigma:F2}");
            sb.AppendLine($"normalExponent={profile.NormalSigma:F1}");
            sb.AppendLine();

            sb.AppendLine("[Compatibility]");
            sb.AppendLine("multiModChaining=1");

            return sb.ToString();
        }

        public static void SaveConfigToPath(string filePath, GameProfile? profile = null)
        {
            try
            {
                string dir = Path.GetDirectoryName(filePath)!;
                if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                {
                    Directory.CreateDirectory(dir);
                }

                string iniContent = profile != null 
                    ? GenerateCompleteIni(profile) 
                    : "; AetherPulse Runtime Configuration\n\n[Pacing]\nenablePacing=1\ntargetFps=180\nhalfInterval=1\nantiLag2=1\nhudPreservationMask=1\nemaAlpha=0.125\nenforceFlipDiscard=1\nmaxFrameLatency=1\nspinYieldPrecisionUs=500\n\n[Upscaling]\nnativeAA=0\nreactiveMaskOptimization=1\noverrideRCAS=1\nrcasSharpness=0.35\nautoCalculateMipLod=1\nmanualMipLodBias=-0.58\nreactiveMaskSensitivity=0.10\ndrsFloorScale=67\n\n[RayRegeneration]\nenableRayRegen=1\nfp16RadianceClamp=1\nenableNRC=1\ndenoiseReflection=1\ndenoiseShadowAO=1\nglossyRadianceFilter=1\nhdrExposureClamping=1\nperceptualColorCorrection=1\ndisocclusionGhostingFilter=1\nroughnessThreshold=0.50\nspatialWaveletIterations=3\ntemporalHistoryWeight=0.85\ndepthSigma=1.00\nnormalExponent=32.0\n\n[Compatibility]\nmultiModChaining=1\n";

                File.WriteAllText(filePath, iniContent);
            }
            catch { }
        }

        public static void SaveConfigDebounced(GameProfile? profile)
        {
            if (profile == null) return;

            lock (_syncLock)
            {
                _debounceCts?.Cancel();
                _debounceCts = new CancellationTokenSource();
                var token = _debounceCts.Token;

                Task.Delay(50, token).ContinueWith(t =>
                {
                    if (t.IsCanceled) return;

                    string iniContent = GenerateCompleteIni(profile);
                    try
                    {
                        // 1. Write to Public global handshake
                        File.WriteAllText(@"C:\Users\Public\aetherpulse.ini", iniContent);

                        // 2. Write to target game folder if set
                        if (!string.IsNullOrWhiteSpace(profile.InstallDirectory) && Directory.Exists(profile.InstallDirectory))
                        {
                            string gameIniPath = Path.Combine(profile.InstallDirectory, "aetherpulse.ini");
                            File.WriteAllText(gameIniPath, iniContent);
                        }
                    }
                    catch { }
                }, token);
            }
        }
    }
}
