using System;
using System.IO;
using System.Text;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AppUI.Models
{
    public partial class GameProfile : ObservableObject
    {
        [ObservableProperty]
        private string _id = Guid.NewGuid().ToString("N");

        [ObservableProperty]
        private string _gameName = string.Empty;

        [ObservableProperty]
        private string _executablePath = string.Empty;

        [ObservableProperty]
        private string _installDirectory = string.Empty;

        [ObservableProperty]
        private string _iconPath = string.Empty;

        // Pacing / Frame Generation Configuration
        [ObservableProperty]
        private bool _pacingEnabled = true;

        [ObservableProperty]
        private bool _halfIntervalCadenceEnabled = true;

        [ObservableProperty]
        private string _frameGenMultiplier = "Adaptive (Dynamic Target FPS)";

        [ObservableProperty]
        private uint _adaptiveTargetFps = 180; // 60 to 360 FPS

        [ObservableProperty]
        private uint _targetFpsCap = 0; // 0 = automatic EMA tracking

        [ObservableProperty]
        private float _emaAlpha = 0.125f;

        [ObservableProperty]
        private uint _spinYieldMicroseconds = 500;

        [ObservableProperty]
        private bool _forceFlipDiscard = true;

        [ObservableProperty]
        private uint _maxFrameLatency = 1;

        [ObservableProperty]
        private bool _antiLag2Enabled = true;

        [ObservableProperty]
        private bool _hudProtection = true; // HUD Preservation Mask for 2D UI elements

        // Ray Regeneration / Denoiser Configuration
        [ObservableProperty]
        private bool _rayRegenEnabled = true;

        [ObservableProperty]
        private bool _neuralRadianceCache = true; // Neural Radiance Caching (NRC)

        [ObservableProperty]
        private bool _denoiseReflections = true;

        [ObservableProperty]
        private bool _denoiseShadows = true;

        [ObservableProperty]
        private bool _glossyRadianceFilter = true;

        [ObservableProperty]
        private float _roughnessThreshold = 0.5f;

        [ObservableProperty]
        private uint _spatialFilterPasses = 2;

        [ObservableProperty]
        private float _temporalWeight = 0.85f;

        [ObservableProperty]
        private float _depthSigma = 1.0f;

        [ObservableProperty]
        private float _normalSigma = 64.0f;

        [ObservableProperty]
        private bool _forceAutoExposure = true;

        [ObservableProperty]
        private bool _colorSpaceCorrect = true;

        [ObservableProperty]
        private bool _disocclusionFilterEnabled = true;

        [ObservableProperty]
        private bool _forceUnlockInGameRR = true;

        // FSR 4 Upscaling & Sharpening Configuration
        [ObservableProperty]
        private string _upscalingMode = "Quality";

        [ObservableProperty]
        private bool _nativeAA = false; // Native AA (FSR Native resolution render pass)

        [ObservableProperty]
        private bool _reactiveMask = true; // Reactive Mask Optimization for fast HUD elements

        [ObservableProperty]
        private bool _enableRCASOverride = true;

        [ObservableProperty]
        private float _sharpness = 0.35f;

        [ObservableProperty]
        private bool _autoLODBias = true;

        [ObservableProperty]
        private float _textureLODBias = -0.58f;

        [ObservableProperty]
        private float _reactiveMaskSensitivity = 0.10f;

        [ObservableProperty]
        private uint _clampMinRenderScale = 67;

        [ObservableProperty]
        private bool _bridgeDLSSToFSR4 = true;

        // Deployment & Runtime State
        [ObservableProperty]
        private DeploymentMode _mode = DeploymentMode.DxgiProxy;

        [ObservableProperty]
        private bool _isHookDeployed;

        [ObservableProperty]
        private bool _isGameRunning;

        [ObservableProperty]
        private bool _hasAntiCheatWarning;

        [ObservableProperty]
        private string _detectedAntiCheatName = string.Empty;

        [ObservableProperty]
        private DateTime? _lastDeployedAt;

        public string ExecutableName => !string.IsNullOrEmpty(ExecutablePath) ? Path.GetFileName(ExecutablePath) : string.Empty;

        public string GenerateIniContent()
        {
            var sb = new StringBuilder();
            sb.AppendLine("; AetherPulse Runtime Configuration File");
            sb.AppendLine("; Generated by AetherPulse AppUI Profile Manager");
            sb.AppendLine();
            sb.AppendLine("[Upscaling]");
            sb.AppendLine($"Mode={UpscalingMode}");
            sb.AppendLine($"NativeAA={(NativeAA ? "true" : "false")}");
            sb.AppendLine($"ReactiveMask={(ReactiveMask ? "true" : "false")}");
            sb.AppendLine($"BridgeDLSS_To_FSR4={(BridgeDLSSToFSR4 ? "1" : "0")}");
            sb.AppendLine($"EnableRCASOverride={(EnableRCASOverride ? "true" : "false")}");
            sb.AppendLine($"Sharpness={Sharpness:F2}");
            sb.AppendLine($"AutoLODBias={(AutoLODBias ? "true" : "false")}");
            sb.AppendLine($"TextureLODBias={TextureLODBias:F2}");
            sb.AppendLine($"ReactiveMaskSensitivity={ReactiveMaskSensitivity:F2}");
            sb.AppendLine($"ClampMinRenderScale={ClampMinRenderScale}");
            sb.AppendLine();
            sb.AppendLine("[RayRegeneration]");
            sb.AppendLine($"Enabled={(RayRegenEnabled ? "true" : "false")}");
            sb.AppendLine($"NeuralRadianceCache={(NeuralRadianceCache ? "true" : "false")}");
            sb.AppendLine($"DenoiseReflections={(DenoiseReflections ? "true" : "false")}");
            sb.AppendLine($"DenoiseShadows={(DenoiseShadows ? "true" : "false")}");
            sb.AppendLine($"GlossyRadianceFilter={(GlossyRadianceFilter ? "true" : "false")}");
            sb.AppendLine($"RoughnessThreshold={RoughnessThreshold:F2}");
            sb.AppendLine($"SpatialFilterPasses={SpatialFilterPasses}");
            sb.AppendLine($"TemporalWeight={TemporalWeight:F2}");
            sb.AppendLine($"DepthSigma={DepthSigma:F2}");
            sb.AppendLine($"NormalSigma={NormalSigma:F1}");
            sb.AppendLine($"ForceAutoExposure={(ForceAutoExposure ? "true" : "false")}");
            sb.AppendLine($"ColorSpaceCorrect={(ColorSpaceCorrect ? "true" : "false")}");
            sb.AppendLine($"EnableDisocclusionFilter={(DisocclusionFilterEnabled ? "true" : "false")}");
            sb.AppendLine();
            sb.AppendLine("[FrameGeneration]");
            sb.AppendLine($"Enabled={(PacingEnabled ? "true" : "false")}");
            string multiplierKey = FrameGenMultiplier switch
            {
                var s when s.Contains("Off") || s.Contains("1x") => "x1",
                var s when s.StartsWith("2x") => "x2",
                var s when s.StartsWith("3x") => "x3",
                var s when s.StartsWith("4x") => "x4",
                var s when s.StartsWith("5x") => "x5",
                var s when s.StartsWith("6x") => "x6",
                _ => "Adaptive"
            };
            sb.AppendLine($"MultiplierMode={multiplierKey}");
            sb.AppendLine($"TargetFPS={AdaptiveTargetFps}");
            sb.AppendLine($"HUDProtection={(HudProtection ? "true" : "false")}");
            sb.AppendLine($"EnableHalfIntervalPacing={(HalfIntervalCadenceEnabled ? "true" : "false")}");
            sb.AppendLine($"TargetFpsCap={TargetFpsCap}");
            sb.AppendLine($"EmaAlpha={EmaAlpha:F3}");
            sb.AppendLine($"SpinYieldMicroseconds={SpinYieldMicroseconds}");
            sb.AppendLine($"ForceFlipDiscard={(ForceFlipDiscard ? "true" : "false")}");
            sb.AppendLine($"MaxFrameLatency={MaxFrameLatency}");
            sb.AppendLine($"EnableAntiLag2={(AntiLag2Enabled ? "true" : "false")}");
            sb.AppendLine();
            sb.AppendLine("[Streamline]");
            sb.AppendLine($"ForceUnlockInGameRR={(RayRegenEnabled && ForceUnlockInGameRR ? "true" : "false")}");
            sb.AppendLine($"BridgeDLSS_To_FSR4={(BridgeDLSSToFSR4 ? "1" : "0")}");
            sb.AppendLine();
            sb.AppendLine("[Telemetry]");
            sb.AppendLine("EnableSharedMemory=true");
            sb.AppendLine("UpdateIntervalMs=16");
            return sb.ToString();
        }
    }
}
